{% set version = "3.0.0" %}

package:
  name: pyviz_comms
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyviz_comms/pyviz_comms-{{ version }}.tar.gz
  sha256: f4ca91e4157a64e3abed7cc249e60b9a8d2532f8832f1cb075914d19337d2ba6

build:
  number: 0
  skip: true  # [py<38 or s390x]
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  host:
    - python
    - hatchling >=1.5.0
    - hatch-nodejs-version
    - hatch-jupyter-builder >=0.8.2
    - pip
  run:
    - python
    - param
  run_constrained:
    - jupyterlab >=4,<5

test:
  imports:
    - pyviz_comms
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://holoviz.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Bidirectional notebook communication for HoloViz libraries
  description: |
    Bidirectional notebook communication for HoloViz libraries
  dev_url: https://github.com/holoviz/pyviz_comms
  doc_url: https://github.com/holoviz/pyviz_comms#readme

extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
  skip-lints:
    - host_section_needs_exact_pinnings
