{% set version = "0.7.5" %}

package:
  name: pyviz_comms
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyviz_comms/pyviz_comms-{{ version }}.tar.gz
  sha256: daa758ec7d7b519b0e315757cdedbf4b385600a5bcbb71af66100804b98423c9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  host:
    - python
    - param
    - pip
  run:
    - python
    - param

test:
  imports:
    - pyviz_comms

about:
  home: https://www.pyviz.org
  summary: Bidirectional communication for PyViz
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
