{% set version = "2.3.0" %}

package:
  name: pyviz_comms
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyviz_comms/pyviz_comms-{{ version }}.tar.gz
  sha256: 44709b2e639e84eb1ae7be5eaf3e28a9be7932d29a8cefce1cd603cb3904ad9c

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - param
    - pip
    - jupyter-packaging >=0.7.9,<0.8
    - jupyterlab >=3.0,<4
    - notebook
    - setuptools
    - twine
    - rfc3986
    - keyring
    - wheel
  run:
    - python
    - param

test:
  imports:
    - pyviz_comms
  requires:
    - pip
  commnads:
    - pip check

about:
  home: https://holoviz.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Bidirectional notebook communication for HoloViz libraries
  description: |
    Bidirectional notebook communication for HoloViz libraries
  dev_url: https://github.com/holoviz/pyviz_comms
  doc_url: https://github.com/holoviz/pyviz_comms#readme

extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
  skip-lints:
    - host_section_needs_exact_pinnings
