{% set version = "0.7.2" %}

package:
  name: pyviz_comms
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyviz_comms/pyviz_comms-{{ version }}.tar.gz
  sha256: c1722a496b08eb20ae3f2fedcc1ebcd207567b62e6453c7198a0b8f78ae96049

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

  
requirements:
  host:
    - python
    - param
    - pip
  run:
    - python
    - param

test:
  imports:
    - pyviz_comms

about:
  home: https://www.pyviz.org
  summary: Bidirectional communication for PyViz
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
