{% set version = "3.0.6" %}

package:
  name: pyviz_comms
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pyviz_comms/pyviz_comms-{{ version }}.tar.gz
  sha256: 73d66b620390d97959b2c4d8a2c0778d41fe20581be4717f01e46b8fae8c5695

build:
  number: 0
  skip: true  # [py<38 or s390x]
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  host:
    - python
    - hatchling >=1.5.0
    - hatch-nodejs-version
    - hatch-jupyter-builder >=0.8.2
    - pip
    - jupyterlab >=4.0.0,<5
  run:
    - python
    - param
  run_constrained:
    - jupyterlab >=4.0,<5.dev0
    - setuptools >=40.8.0

test:
  imports:
    - pyviz_comms
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://holoviz.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Bidirectional notebook communication for HoloViz libraries
  description: |
    Bidirectional notebook communication for HoloViz libraries
  dev_url: https://github.com/holoviz/pyviz_comms
  doc_url: https://github.com/holoviz/pyviz_comms#readme

extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
  skip-lints:
    - host_section_needs_exact_pinnings
