{% set version = "2.1.0" %}

package:
  name: pyviz_comms
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyviz_comms/pyviz_comms-{{ version }}.tar.gz
  sha256: f4a7126f318fb6b964fef3f92fa55bc46b9218f62a8464a8b18e968b3087dbc0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=2.7
    - param
    - pip
    - jupyter-packaging >=0.7.9
    - jupyterlab >=3.0
    - notebook
    - setuptools
    - twine
    - rfc3986
    - keyring
    - wheel
  run:
    - python >=2.7
    - param

test:
  imports:
    - pyviz_comms
  requires:
    - pip
  commnads:
    - pip check

about:
  home: https://www.holoviz.org
  summary: Bidirectional communication for PyViz
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  dev_url: https://github.com/holoviz/pyviz_comms

extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
