travis:
  secure:
    BINSTAR_TOKEN: SpIkK7fbycJm3T9UcFxVfOena1TCceYJC5T5lnK/muCQQTjNqkpSYyk3BxnkA74VWMsqSNPxb7Kz+ujcKZ3lTx1c96LzW4IuOc6472JfzAOJ+kp/6CNmsbcv4AFBA4LPbOE9ZLX0c1W0zKDDUkQryXQV3IZsNDfQZK1PBgu9jxc8WKtYXfoznPsP3ZQRoIE4vjgDlMQknpog8XcrK3SP8hzGTbb3lWo5Vx4PajeDBpwxAIW+XkcFDy8jdmjgxvuG2pXxIH9XwbuswZFXIUS0i5KKBLWWR0ASbIUN0ZoC/M6b4Yhpdms6HVlU8fSabpQzyrT2q1nyCf2MYTcGZ4jHh9zeIKfwRgw1gSXXRujrZySyoEcFFmefJCin4kSVDrJiRwbjb0PaWpkkc5AUMHq6RMPhKzCLVkdjxqsuoS1JYFNnkUoqrXUehfvbED4gfu+WQkeFhZJrTXzx595zJYgPyDRDa+P6xIVf/o+j8/TX9BKkx/HQtY0EKfzcePr76xLNCpbppawsGaClxjBq8Anw+BFts9cFj9grawezv7sD+BtmsgNB2FbUqOFIS14THw9YJMnSRI8com60F9crE/fUb+ShDJAhG/5sXySsg1wwDsXQx7wpnWFptioMHeo2s1w/Ta8GCInpIWjALnnYkrcHSdF/Qy/q9Ds90PJw/Gk6TFs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
