travis:
  secure:
    BINSTAR_TOKEN: S43JHmH8MFyMNRhlQPcCyj+4W4uDWfTHN+FuiVGKZ++RkAOaCcnc5zGPRNoz+C0S4h+veJgJvtPuvvsElzii3aS3ZsJCtB4XQUpLMia9HVsmNCLH18/Acqnotrvp2EbMB06P8llr1J1u4yLKplH5bKFDBKadB6UR6RVE8qLCNV33OBuVNUc9jaJ8Fq8hxXD5jKrCJuAzurMxNV0Ccaw7853F2HP41iTL38lrg9zjjjmcVpVd9bUcOJFzKHDRDniV3d93bDTYpEFiDHAtmpqXIUVSNHIe9Z66MhfUOYwVW72KPx1xyIxHotyCEgBWYqYBKUO7CneRxjzuAgkjE7p+W3/kzYFqS+aHfOQK8Qa82iNlxib9kF+JlDGolNM0FqEkynXesEwQ+n4uf4jrlN4zryR11sklZpI7Yu9P5Ha59zQLsQ2ecKCghVZ939nAhT0lTi9Sszp/7GPHqnOng5IfmkpG2qSCYEK6arGXUZwz7LIIjLxfezucmtpCBCt1C0ubp260CllIsAo/oI9rn9kokijd7q8O5rnlKrARjIZTDmNw52ioNJUWnpfIq1Jj6oYJ0H/cS0R8+7L3/FV9ST/RGdab7rUIwpnncTPJbP12n5QP/xMetUxxnsIM+Ub8fNpW3ilBCvxm7GTgjgO/be2d5j4HCujvMhykwMp1q9gwnmU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
